/**
 * Pre-computes the dotted world map SVG path and projection lookup at build time.
 * This eliminates the expensive runtime `createMap()` call (~1,000ms of main-thread blocking)
 * by moving GeoJSON parsing and point-in-polygon sampling to build time.
 *
 * Run: pnpm generate-map
 */
import { writeFileSync } from 'node:fs'

import { createMap } from 'svg-dotted-map'

const WIDTH = 150
const HEIGHT = 75
const MAP_SAMPLES = 5000
const DOT_RADIUS = 0.25

const mapData = createMap({
  width: WIDTH,
  height: HEIGHT,
  mapSamples: MAP_SAMPLES,
})

// Compute stagger data
const sorted = [...mapData.points].sort(
  (a: { x: number; y: number }, b: { x: number; y: number }) =>
    a.y - b.y || a.x - b.x,
)
const rowMap = new Map<number, number>()
let step = 0
let prevY = Number.NaN
let prevXInRow = Number.NaN

for (const p of sorted) {
  if (p.y !== prevY) {
    prevY = p.y
    prevXInRow = Number.NaN
    if (!rowMap.has(p.y)) rowMap.set(p.y, rowMap.size)
  }
  if (!Number.isNaN(prevXInRow)) {
    const delta = p.x - prevXInRow
    if (delta > 0) step = step === 0 ? delta : Math.min(step, delta)
  }
  prevXInRow = p.x
}
const xStep = step || 1

// Build SVG path string
const parts: string[] = []
const r = DOT_RADIUS
for (const point of mapData.points) {
  const rowIndex = rowMap.get(point.y) ?? 0
  const offsetX = rowIndex % 2 === 1 ? xStep / 2 : 0
  const cx = point.x + offsetX
  const cy = point.y
  parts.push(
    `M${cx - r},${cy}a${r},${r} 0 1,0 ${r * 2},0a${r},${r} 0 1,0 -${r * 2},0`,
  )
}
const dotsPath = parts.join('')

// Build projection lookup tables using the library's own addMarkers function.
// The library uses a non-linear (Mercator-like) projection for latitude,
// so we sample every degree and store the results for runtime interpolation.

// Longitude -> X is linear; extract scale and origin from two widely separated
// points to minimise grid-snapping error
const lngTest = mapData.addMarkers([
  { lat: 0, lng: -170 },
  { lat: 0, lng: 170 },
]) as Array<{ x: number; y: number }>
const lngScaleX = (lngTest[1].x - lngTest[0].x) / 340
const lngOriginX = lngTest[0].x - -170 * lngScaleX

// Latitude -> Y is non-linear; build a dense lookup table
const latEntries: Array<[number, number]> = []
for (let lat = -70; lat <= 85; lat++) {
  const result = mapData.addMarkers([{ lat, lng: 0 }]) as Array<{ y: number }>
  latEntries.push([lat, result[0].y])
}

// Stagger data: yToRowIndex as [y, index] pairs
const yToRowEntries = Array.from(rowMap.entries())

const output = `/**
 * Auto-generated by scripts/generate-map-data.ts
 * Do not edit manually. Run: pnpm generate-map
 */

/** Pre-computed SVG path for all world map dots (width=150, height=75, samples=5000, dotRadius=0.25) */
export const MAP_DOTS_PATH = '${dotsPath}'

/** Longitude projection: x = LNG_ORIGIN_X + lng * LNG_SCALE_X */
export const LNG_ORIGIN_X = ${lngOriginX}
export const LNG_SCALE_X = ${lngScaleX}

/**
 * Latitude-to-Y lookup table for non-linear (Mercator-like) projection.
 * Entries are [latitude, svgY] pairs sampled every 1 degree.
 * Use linear interpolation between entries at runtime.
 */
export const LAT_TO_Y: ReadonlyArray<readonly [number, number]> = [${latEntries.map(([lat, y]) => `[${lat},${y}]`).join(',')}]

/** Stagger grid data: xStep and y-to-row-index mapping */
export const MAP_STAGGER = {
  xStep: ${xStep},
  yToRowIndex: new Map<number, number>([${yToRowEntries.map(([y, i]) => `[${y},${i}]`).join(',')}]),
} as const

export const MAP_DIMENSIONS = {
  width: ${WIDTH},
  height: ${HEIGHT},
} as const
`

writeFileSync('src/generated/map-data.ts', output)
console.log(
  `Generated src/generated/map-data.ts (${dotsPath.length} chars path, ${latEntries.length} lat entries, ${yToRowEntries.length} row entries)`,
)
