/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OgIndexRouteImport } from './routes/og/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogRssRouteRouteImport } from './routes/blog/rss/route'
import { Route as BlogOgIndexRouteImport } from './routes/blog/og/index'
import { Route as BlogSlugIndexRouteImport } from './routes/blog/$slug/index'
import { Route as BlogSlugPostDotmdRouteRouteImport } from './routes/blog/$slug/post[.md]/route'
import { Route as BlogSlugOgIndexRouteImport } from './routes/blog/$slug/og/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgIndexRoute = OgIndexRouteImport.update({
  id: '/og/',
  path: '/og/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRssRouteRoute = BlogRssRouteRouteImport.update({
  id: '/blog/rss',
  path: '/blog/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogOgIndexRoute = BlogOgIndexRouteImport.update({
  id: '/blog/og/',
  path: '/blog/og/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugIndexRoute = BlogSlugIndexRouteImport.update({
  id: '/blog/$slug/',
  path: '/blog/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugPostDotmdRouteRoute = BlogSlugPostDotmdRouteRouteImport.update({
  id: '/blog/$slug/post.md',
  path: '/blog/$slug/post.md',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugOgIndexRoute = BlogSlugOgIndexRouteImport.update({
  id: '/blog/$slug/og/',
  path: '/blog/$slug/og/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/rss': typeof BlogRssRouteRoute
  '/blog/': typeof BlogIndexRoute
  '/og/': typeof OgIndexRoute
  '/blog/$slug/post.md': typeof BlogSlugPostDotmdRouteRoute
  '/blog/$slug/': typeof BlogSlugIndexRoute
  '/blog/og/': typeof BlogOgIndexRoute
  '/blog/$slug/og/': typeof BlogSlugOgIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/rss': typeof BlogRssRouteRoute
  '/blog': typeof BlogIndexRoute
  '/og': typeof OgIndexRoute
  '/blog/$slug/post.md': typeof BlogSlugPostDotmdRouteRoute
  '/blog/$slug': typeof BlogSlugIndexRoute
  '/blog/og': typeof BlogOgIndexRoute
  '/blog/$slug/og': typeof BlogSlugOgIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/rss': typeof BlogRssRouteRoute
  '/blog/': typeof BlogIndexRoute
  '/og/': typeof OgIndexRoute
  '/blog/$slug/post.md': typeof BlogSlugPostDotmdRouteRoute
  '/blog/$slug/': typeof BlogSlugIndexRoute
  '/blog/og/': typeof BlogOgIndexRoute
  '/blog/$slug/og/': typeof BlogSlugOgIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/blog/rss'
    | '/blog/'
    | '/og/'
    | '/blog/$slug/post.md'
    | '/blog/$slug/'
    | '/blog/og/'
    | '/blog/$slug/og/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/blog/rss'
    | '/blog'
    | '/og'
    | '/blog/$slug/post.md'
    | '/blog/$slug'
    | '/blog/og'
    | '/blog/$slug/og'
  id:
    | '__root__'
    | '/'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/blog/rss'
    | '/blog/'
    | '/og/'
    | '/blog/$slug/post.md'
    | '/blog/$slug/'
    | '/blog/og/'
    | '/blog/$slug/og/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogRssRouteRoute: typeof BlogRssRouteRoute
  BlogIndexRoute: typeof BlogIndexRoute
  OgIndexRoute: typeof OgIndexRoute
  BlogSlugPostDotmdRouteRoute: typeof BlogSlugPostDotmdRouteRoute
  BlogSlugIndexRoute: typeof BlogSlugIndexRoute
  BlogOgIndexRoute: typeof BlogOgIndexRoute
  BlogSlugOgIndexRoute: typeof BlogSlugOgIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/': {
      id: '/og/'
      path: '/og'
      fullPath: '/og/'
      preLoaderRoute: typeof OgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/rss': {
      id: '/blog/rss'
      path: '/blog/rss'
      fullPath: '/blog/rss'
      preLoaderRoute: typeof BlogRssRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/og/': {
      id: '/blog/og/'
      path: '/blog/og'
      fullPath: '/blog/og/'
      preLoaderRoute: typeof BlogOgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug/': {
      id: '/blog/$slug/'
      path: '/blog/$slug'
      fullPath: '/blog/$slug/'
      preLoaderRoute: typeof BlogSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug/post.md': {
      id: '/blog/$slug/post.md'
      path: '/blog/$slug/post.md'
      fullPath: '/blog/$slug/post.md'
      preLoaderRoute: typeof BlogSlugPostDotmdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug/og/': {
      id: '/blog/$slug/og/'
      path: '/blog/$slug/og'
      fullPath: '/blog/$slug/og/'
      preLoaderRoute: typeof BlogSlugOgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogRssRouteRoute: BlogRssRouteRoute,
  BlogIndexRoute: BlogIndexRoute,
  OgIndexRoute: OgIndexRoute,
  BlogSlugPostDotmdRouteRoute: BlogSlugPostDotmdRouteRoute,
  BlogSlugIndexRoute: BlogSlugIndexRoute,
  BlogOgIndexRoute: BlogOgIndexRoute,
  BlogSlugOgIndexRoute: BlogSlugOgIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
